# Stage-1 (Build stage)
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install && npm run build
COPY . .

# Stage-2 (Production stage)
FROM gcr.io/distroless/nodejs22-debian12
WORKDIR /app
COPY --from=builder /app .
EXPOSE 5173
CMD ["npm","run","dev"]
