
services:
     shopping-app:
           build:
               context: .
               dockerfile: Dockerfile-multi
           container_name: shopping-app
           ports:
              - "5173:5173"
           restart: always
           healthcheck:
                    test: ["CMD", "curl", "-f", "http://localhost:5173"]
                    interval: 10s
                    retries: 5
                    timeout: 10s
           networks:
                 - shopping-app
networks:
  shopping-app:
    driver: bridge                   
